(function(){'use strict';
var g="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},k="object"===typeof g.global&&g.global?g.global:"object"===typeof global&&global&&global.Object===Object?global:this;g.global=k;var aa="object"===typeof g.exportsNamespace&&g.exportsNamespace?g.exportsNamespace:k;g.exportsNamespace=aa;k.Object.freeze(g);var ba={semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1};k.Object.freeze(ba);k.Object.freeze(ba.semantics);
var l=k.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ca=k.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},da=0,ea=k.WeakMap?new k.WeakMap:null;function p(a){return function(b,c){return!(!b||!b.a||b.a.A!==c||b.a.y!==a)}}function fa(a){for(var b in a)return b}
function ga(a,b){return new a.O(b)}function ha(a,b,c){var d=new a.O(b[c]);if(c<b.length-1){a=a.B;c+=1;for(var e=d.d,f=0;f<e.length;f++)e[f]=ha(a,b,c)}return d}function ia(a){switch(typeof a){case "string":return q(ja);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?q(ka):b<<16>>16===b&&1/b!==1/-0?q(la):q(ma):"number"===typeof a?q(na):q(oa);case "boolean":return q(pa);case "undefined":return q(qa);default:return null===a?a.Ua():ra(a)?q(sa):a&&a.a?q(a.a):null}}
function ta(a){switch(typeof a){case "string":return ua(va(),a);case "number":return xa(ya(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.a||null===a?a.I():null===ea?42:za(a)}}function Aa(a,b){for(var c=k.Object.getPrototypeOf,d=k.Object.getOwnPropertyDescriptor,e=c(a);null!==e;){var f=d(e,b);if(void 0!==f)return f;e=c(e)}}function Ba(a,b,c){a=Aa(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function Ca(a,b,c,d){a=Aa(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new k.TypeError("super has no setter '"+c+"'.");}
var za=null!==ea?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return ta(a);default:if(null===a)return 0;var b=ea.get(a);void 0===b&&(da=b=da+1|0,ea.set(a,b));return b}}:function(a){if(a&&a.a){var b=a.$idHashCode$0;if(void 0!==b)return b;if(k.Object.isSealed(a))return 42;da=b=da+1|0;return a.$idHashCode$0=b}return null===a?0:ta(a)};this.__ScalaJSExportsNamespace=aa;
function s(){this.K=this.O=void 0;this.y=this.B=this.k=null;this.A=0;this.U=null;this.G="";this.j=this.E=this.F=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function v(a,b,c){var d=new s;d.k={};d.B=null;d.U=a;d.G=b;d.j=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function w(a,b,c,d,e,f,m){var n=new s,u=fa(a);f=f||function(a){return!!(a&&a.a&&a.a.k[u])};m=m||function(a,b){return!!(a&&a.a&&a.a.A===b&&a.a.y.k[u])};n.K=e;n.k=c;n.G="L"+b+";";n.j=m;n.name=b;n.isInterface=!1;n.isRawJSType=!!d;n.isInstance=f;return n}
function Da(a){function b(a){if("number"===typeof a){this.d=Array(a);for(var b=0;b<a;b++)this.d[b]=e}else this.d=a}var c=new s,d=a.U,e="longZero"==d?x().r:d;b.prototype=new y;b.prototype.a=c;var d="["+a.G,f=a.y||a,m=a.A+1;c.O=b;c.K=Ea;c.k={b:1,Wa:1,p:1};c.B=a;c.y=f;c.A=m;c.U=null;c.G=d;c.F=void 0;c.E=void 0;c.j=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return f.j(a,m)};return c}function q(a){if(!a.F){var b=new z;b.H=a;a.F=b}return a.F}
function A(a){a.E||(a.E=Da(a));return a.E}s.prototype.getFakeInstance=function(){return this===ja?"some string":this===pa?!1:this===ka||this===la||this===ma||this===na||this===oa?0:this===sa?x().r:this===qa?void 0:{a:this}};s.prototype.getSuperclass=function(){return this.K?q(this.K):null};s.prototype.getComponentType=function(){return this.B?q(this.B):null};s.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=A(b);return ha(b,a,0)};
var Fa=v(!1,"Z","boolean"),Ga=v(0,"C","char"),Ha=v(0,"B","byte"),Ia=v(0,"S","short"),Ja=v(0,"I","int"),Ka=v("longZero","J","long"),La=v(0,"F","float"),Ma=v(0,"D","double");Fa.j=p(Fa);Ga.j=p(Ga);Ha.j=p(Ha);Ia.j=p(Ia);Ja.j=p(Ja);Ka.j=p(Ka);La.j=p(La);Ma.j=p(Ma);function B(){}function y(){}y.prototype=B.prototype;B.prototype.c=function(){return this};B.prototype.x=function(){var a=Na(ia(this)),b=(+(this.I()>>>0)).toString(16);return a+"@"+b};B.prototype.I=function(){return za(this)};B.prototype.toString=function(){return this.x()};var Ea=w({b:0},"java.lang.Object",{b:1},void 0,void 0,function(a){return null!==a},function(a,b){var c=a&&a.a;if(c){var d=c.A||0;return!(d<b)&&(d>b||!c.y.isPrimitive)}return!1});B.prototype.a=Ea;
function C(){this.m=this.l=this.M=this.o=this.n=0}C.prototype=new y;C.prototype.constructor=C;function Oa(a,b,c){a.l-=b;a.m-=c;-3>a.l?a.l=-3:3<a.l&&(a.l=3);-3>a.m?a.m=-3:3<a.m&&(a.m=3)}var Pa=w({ga:0},"Point",{ga:1,b:1});C.prototype.a=Pa;function G(){this.D=0;this.C=this.w=null}G.prototype=new y;G.prototype.constructor=G;
G.prototype.t=function(a){this.D=a;a=[];for(var b=0;30>b;){var c=new C,d=+k.Math.random()*(H().g.width|0),e=+k.Math.random()*(H().g.height|0);c.n=d;c.o=e;c.M=2*3.141592653589793*+k.Math.random();c.l=+k.Math.sin(c.M);c.m=+k.Math.cos(c.M);a.push(c);b=1+b|0}this.w=ga(A(Pa),a);this.C=null;return this};var Ra=w({ha:0},"System",{ha:1,b:1});G.prototype.a=Ra;function z(){this.H=null}z.prototype=new y;z.prototype.constructor=z;function Na(a){return a.H.name}
z.prototype.x=function(){return(this.H.isInterface?"interface ":this.H.isPrimitive?"":"class ")+Na(this)};z.prototype.a=w({qa:0},"java.lang.Class",{qa:1,b:1});function Sa(){}Sa.prototype=new y;Sa.prototype.constructor=Sa;function Ta(){}Ta.prototype=Sa.prototype;function Ua(){}Ua.prototype=new y;Ua.prototype.constructor=Ua;function Va(){}Va.prototype=Ua.prototype;function I(){this.v=!1;this.Y=this.na=this.J=this.z=null;this.N=!1;this.ba=this.Z=0}I.prototype=new y;I.prototype.constructor=I;
I.prototype.c=function(){Wa=this;this.z=(this.v=!!(k.ArrayBuffer&&k.Int32Array&&k.Float32Array&&k.Float64Array))?new k.ArrayBuffer(8):null;this.J=this.v?new k.Int32Array(this.z,0,2):null;this.na=this.v?new k.Float32Array(this.z,0,2):null;this.Y=this.v?new k.Float64Array(this.z,0,1):null;if(this.v)this.J[0]=16909060,a=1===((new k.Int8Array(this.z,0,8))[0]|0);else var a=!0;this.Z=(this.N=a)?0:1;this.ba=this.N?1:0;return this};
function xa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.v)a.Y[0]=b,c=Xa(Ya((new J).t(a.J[a.Z]|0)),Za((new J).i(-1,0),(new J).t(a.J[a.ba]|0)));else{if(b!==b)var c=!1,d=2047,e=+k.Math.pow(2,51);else if(Infinity===b||-Infinity===b)c=0>b,d=2047,e=0;else if(0===b)c=-Infinity===1/b,e=d=0;else{var f=(c=0>b)?-b:b;if(f>=+k.Math.pow(2,-1022)){var d=+k.Math.pow(2,52),e=+k.Math.log(f)/0.6931471805599453,e=+k.Math.floor(e)|0,e=1023>e?e:1023,m=f/+k.Math.pow(2,e)*d,f=+k.Math.floor(m),m=m-f,f=0.5>m?f:
0.5<m?1+f:0!==f%2?1+f:f;2<=f/d&&(e=1+e|0,f=1);1023<e?(e=2047,f=0):(e=1023+e|0,f-=d);d=e;e=f}else d=f/+k.Math.pow(2,-1074),e=+k.Math.floor(d),f=d-e,d=0,e=0.5>f?e:0.5<f?1+e:0!==e%2?1+e:e}e=+e;f=e|0;c=Xa(Ya((new J).t((c?-2147483648:0)|(d|0)<<20|e/4294967296|0)),Za((new J).i(-1,0),(new J).t(f)))}return c.f^c.h}I.prototype.a=w({Da:0},"scala.scalajs.runtime.Bits$",{Da:1,b:1});var Wa=void 0;function ya(){Wa||(Wa=(new I).c());return Wa}function K(){this.Na=null;this.Ta=!1}K.prototype=new y;
K.prototype.constructor=K;K.prototype.c=function(){return this};function ua(a,b){for(var c=0,d=1,e=-1+(b.length|0)|0;0<=e;)c=c+l(65535&(b.charCodeAt(e)|0),d)|0,d=l(31,d),e=-1+e|0;return c}K.prototype.a=w({Fa:0},"scala.scalajs.runtime.RuntimeString$",{Fa:1,b:1});var $a=void 0;function va(){$a||($a=(new K).c());return $a}function L(){}L.prototype=new y;L.prototype.constructor=L;L.prototype.c=function(){return this};function ab(a,b){return b&&b.a&&b.a.k.T?b.s:b}
L.prototype.a=w({Ga:0},"scala.scalajs.runtime.package$",{Ga:1,b:1});var bb=void 0;function cb(){bb||(bb=(new L).c());return bb}var qa=w({Ha:0},"scala.runtime.BoxedUnit",{Ha:1,b:1},void 0,void 0,function(a){return void 0===a});function M(){}M.prototype=new y;M.prototype.constructor=M;M.prototype.c=function(){return this};M.prototype.a=w({Ia:0},"scala.runtime.BoxesRunTime$",{Ia:1,b:1});var db=void 0;function N(){}N.prototype=new y;N.prototype.constructor=N;N.prototype.c=function(){return this};
N.prototype.a=w({Ja:0},"scala.runtime.ScalaRunTime$",{Ja:1,b:1});var eb=void 0;function O(){this.L=this.e=this.g=null}O.prototype=new y;O.prototype.constructor=O;O.prototype.c=function(){this.L=this.e=this.g=null;return this};
function fb(a,b,c,d){a.g=k.document.getElementById(b);a.e=a.g.getContext("2d");b=[];for(var e=0;e<c;){var f=(new G).t(d);b.push(f);e=1+e|0}a.L=ga(A(Ra),b);k.setInterval(function(){return function(){for(var a=H().L,b=0,c=a.d.length;b<c;){for(var d=a.d[b],e=d.D,f=[],h=0;h<e;){for(var D=d.D,r=[],t=0;t<D;)r.push(0),t=1+t|0;D=ga(A(Ma),r);f.push(D);h=1+h|0}d.C=ga(A(A(Ma)),f);f=d.D;h=1>=f;e=1+(h?0:-1+f|0)|0;0>(h?0:-1+f|0)&&P(Q(),1,f,!1);for(f=1;f!==e;){h=f;r=0>=h;D=1+(r?-1:-1+h|0)|0;0>(r?0:h)&&P(Q(),0,h,
!1);for(r=0;r!==D;){var t=r,$=d.w.d[h],E=d.w.d[t],S=$.n-E.n,wa=$.o-E.o,jb=S/1E6,kb=wa/1E6;Oa($,jb,kb);Oa(E,-jb,-kb);d.C.d[h].d[t]=+k.Math.sqrt(S*S+wa*wa);r=1+r|0}f=1+f|0}d=d.w;e=0;for(f=d.d.length;e<f;){h=d.d[e];if(0>h.n||h.n>(H().g.width|0))h.l=-h.l;h.n+=h.l;if(0>h.o||h.o>(H().g.height|0))h.m=-h.m;h.o+=h.m;e=1+e|0}b=1+b|0}}}((new R).c()),33);k.setInterval(function(){var a=H();a.e.fillStyle="#3069b3";a.e.fillRect(0,0,a.g.width|0,a.g.height|0);a.e.strokeStyle="rgba(255, 255, 255, 0.1)";a.e.lineWidth=
1;var b=(a.g.width|0)/25|0,c=0>b,d=1+(c?-1:b)|0;0>(c?0:2147483646<b?-1:1+b|0)&&P(Q(),0,b,!0);for(b=0;b!==d;)c=b,H().e.beginPath(),H().e.moveTo(l(25,c),0),H().e.lineTo(l(25,c),H().g.height|0),H().e.stroke(),b=1+b|0;b=(a.g.height|0)/25|0;c=0>b;d=1+(c?-1:b)|0;0>(c?0:2147483646<b?-1:1+b|0)&&P(Q(),0,b,!0);for(b=0;b!==d;)c=b,H().e.beginPath(),H().e.moveTo(0,l(25,c)),H().e.lineTo(H().g.width|0,l(25,c)),H().e.stroke(),b=1+b|0;a=a.L;d=0;for(b=a.d.length;d<b;){var c=a.d[d],e=H().e;e.fillStyle="rgba(255, 255, 255, 0.3)";
var f=c.D,h=0>=f,D=1+(h?-1:-1+f|0)|0;0>(h?0:f)&&P(Q(),0,f,!1);for(f=0;f!==D;){var h=f,r=c.w.d[h];e.beginPath();e.arc(r.n,r.o,5,0,6.283185307179586,!1);e.fill();var t=0>=h,$=1+(t?-1:-1+h|0)|0;0>(t?0:h)&&P(Q(),0,h,!1);for(t=0;t!==$;){var E=t,S=c.w.d[E];300>c.C.d[h].d[E]&&(e.strokeStyle="rgba(255, 255, 255, "+0.5*(1-c.C.d[h].d[E]/300)+")",e.beginPath(),e.moveTo(r.n,r.o),e.lineTo(S.n,S.o),e.stroke());t=1+t|0}f=1+f|0}d=1+d|0}},50)}O.prototype.main=function(){};
O.prototype.start=function(a,b,c){fb(this,a,b|0,c|0)};O.prototype.a=w({ea:0},"Bg$",{ea:1,b:1,bb:1});var gb=void 0;function H(){gb||(gb=(new O).c());return gb}aa.Bg=H;var pa=w({oa:0},"java.lang.Boolean",{oa:1,b:1,q:1},void 0,void 0,function(a){return"boolean"===typeof a});function T(){this.eb=this.ma=this.ca=null}T.prototype=new y;T.prototype.constructor=T;function hb(){}hb.prototype=T.prototype;
T.prototype.X=function(){if(void 0===k.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(cb(),b&&b.a&&b.a.k.R?a=b:(a=new U,a.s=b,T.prototype.Q.call(a,null,null)),null!==a)if(a&&a.a&&a.a.k.T)a=a.s;else throw ab(cb(),a);else throw b;}this.stackdata=a}else k.Error.captureStackTrace(this),this.stackdata=this;return this};T.prototype.x=function(){var a=Na(ia(this)),b=this.ca;return null===b?a:a+": "+b};T.prototype.Q=function(a,b){this.ca=a;this.ma=b;this.X();return this};
function V(){this.Ca=this.ya=this.Ba=this.hb=this.gb=this.Xa=this.fb=this.Sa=0}V.prototype=new Va;V.prototype.constructor=V;V.prototype.c=function(){ib=this;this.Ba=ua(va(),"Seq");this.ya=ua(va(),"Map");this.Ca=ua(va(),"Set");return this};V.prototype.a=w({za:0},"scala.util.hashing.MurmurHash3$",{za:1,ab:1,b:1});var ib=void 0;function lb(){}lb.prototype=new y;lb.prototype.constructor=lb;function mb(){}mb.prototype=lb.prototype;lb.prototype.x=function(){return"\x3cfunction0\x3e"};
var ka=w({pa:0},"java.lang.Byte",{pa:1,u:1,b:1,q:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),oa=w({ra:0},"java.lang.Double",{ra:1,u:1,b:1,q:1},void 0,void 0,function(a){return"number"===typeof a});function nb(){T.call(this)}nb.prototype=new hb;nb.prototype.constructor=nb;function ob(){}ob.prototype=nb.prototype;
var na=w({sa:0},"java.lang.Float",{sa:1,u:1,b:1,q:1},void 0,void 0,function(a){return"number"===typeof a}),ma=w({va:0},"java.lang.Integer",{va:1,u:1,b:1,q:1},void 0,void 0,function(a){return(a|0)===a&&1/a!==1/-0}),sa=w({wa:0},"java.lang.Long",{wa:1,u:1,b:1,q:1},void 0,void 0,function(a){return ra(a)}),la=w({xa:0},"java.lang.Short",{xa:1,u:1,b:1,q:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function W(){this.ia=0}W.prototype=new y;W.prototype.constructor=W;
W.prototype.c=function(){this.ia=512;return this};function P(a,b,c,d){throw(new X).P(b+(d?" to ":" until ")+c+" by 1: seqs cannot contain more than Int.MaxValue elements.");}W.prototype.a=w({Aa:0},"scala.collection.immutable.Range$",{Aa:1,b:1,S:1,p:1});var pb=void 0;function Q(){pb||(pb=(new W).c());return pb}function Y(){this.Ka=this.Ma=this.La=this.Ra=this.Qa=this.Pa=0;this.V=this.W=this.ja=this.ka=this.r=null}Y.prototype=new y;Y.prototype.constructor=Y;
Y.prototype.c=function(){qb=this;this.r=(new J).i(0,0);this.ka=(new J).i(1,0);this.ja=(new J).i(-1,-1);this.W=(new J).i(0,-2147483648);this.V=(new J).i(-1,2147483647);return this};function rb(a,b){if(b!==b)return a.r;if(-9223372036854775E3>b)return a.W;if(9223372036854775E3<=b)return a.V;var c=0>b,d=c?-b:b,e=d|0,d=d/4294967296|0;return c?(new J).i(-e|0,0!==e?~d:-d|0):(new J).i(e,d)}Y.prototype.a=w({Ea:0},"scala.scalajs.runtime.RuntimeLong$",{Ea:1,b:1,S:1,p:1});var qb=void 0;
function x(){qb||(qb=(new Y).c());return qb}var ja=w({la:0},"java.lang.String",{la:1,b:1,p:1,Va:1,q:1},void 0,void 0,function(a){return"string"===typeof a});function sb(){T.call(this)}sb.prototype=new ob;sb.prototype.constructor=sb;function tb(){}tb.prototype=sb.prototype;function J(){this.h=this.f=0}J.prototype=new Ta;J.prototype.constructor=J;function Xa(a,b){return(new J).i(a.f|b.f,a.h|b.h)}
J.prototype.x=function(){var a=this.f,b=this.h;return b===a>>31?""+a:0>b?"-"+vb(-a|0,0!==a?~b:-b|0):vb(a,b)};J.prototype.i=function(a,b){this.f=a;this.h=b;return this};function Za(a,b){return(new J).i(a.f&b.f,a.h&b.h)}function Ya(a){return(new J).i(0,a.f<<32)}J.prototype.t=function(a){J.prototype.i.call(this,a,a>>31);return this};J.prototype.I=function(){return this.f^this.h};
function vb(a,b){if(0===(-2097152&b))return""+(4294967296*b+ +(a>>>0));var c,d=(32+ca(1E9)|0)-(0!==b?ca(b):32+ca(a)|0)|0,e=d;0===e?(c=1E9,e=0):32>e?(c=1E9<<e,e=1E9>>>(-e|0)|0|0<<e):(c=0,e=1E9<<e);for(var f=c,m=e,n=a,u=b,e=c=0;0<=d&&0!==(-2097152&u);){var F=n,Qa=u,ub=f,h=m;if(Qa===h?(-2147483648^F)>=(-2147483648^ub):(-2147483648^Qa)>=(-2147483648^h))F=n,n=F-f|0,u=(u-m|0)+((-2147483648^F)<(-2147483648^n)?-1:0)|0,32>d?c|=1<<d:e|=1<<d;d=-1+d|0;F=m>>>1|0;f=f>>>1|0|m<<-1;m=F}d=u;if(0===d?-1147483648<=(-2147483648^
n):-2147483648<=(-2147483648^d))d=4294967296*u+ +(n>>>0),f=d/1E9,n=c,c=u=n+(f|0)|0,e=(e+(f/4294967296|0)|0)+((-2147483648^u)<(-2147483648^n)?1:0)|0,d%=1E9,n=d|0,u=d/4294967296|0;c=[c,e,n,u];e=""+(c["2"]|0);return""+(4294967296*(c["1"]|0)+ +((c["0"]|0)>>>0))+"000000000".substring(e.length|0)+e}function ra(a){return!!(a&&a.a&&a.a.k.da)}J.prototype.a=w({da:0},"scala.scalajs.runtime.RuntimeLong",{da:1,u:1,b:1,p:1,q:1});function wb(){}wb.prototype=new mb;wb.prototype.constructor=wb;function xb(){}
xb.prototype=wb.prototype;function X(){T.call(this)}X.prototype=new tb;X.prototype.constructor=X;X.prototype.P=function(a){T.prototype.Q.call(this,a,null);return this};X.prototype.a=w({ta:0},"java.lang.IllegalArgumentException",{ta:1,aa:1,$:1,R:1,b:1,p:1});function Z(){T.call(this)}Z.prototype=new tb;Z.prototype.constructor=Z;Z.prototype.P=function(a){T.prototype.Q.call(this,a,null);return this};Z.prototype.a=w({ua:0},"java.lang.IndexOutOfBoundsException",{ua:1,aa:1,$:1,R:1,b:1,p:1});
function R(){}R.prototype=new xb;R.prototype.constructor=R;R.prototype.c=function(){return this};R.prototype.a=w({fa:0},"Bg$$anonfun$start$1",{fa:1,db:1,cb:1,b:1,Oa:1,Za:1,S:1,p:1});function U(){T.call(this);this.s=null}U.prototype=new tb;U.prototype.constructor=U;U.prototype.X=function(){this.stackdata=this.s;return this};U.prototype.x=function(){return void 0===this.s?"undefined":this.s.toString()};
U.prototype.I=function(){var a;ib||(ib=(new V).c());var b=-889275714;for(a=0;1>a;){eb||(eb=(new N).c());var c;b:switch(a){case 0:c=this.s;break b;default:throw(new Z).P(""+a);}var d=c;c=void 0;if(null===d)c=0;else if(c=void 0,d&&d.a&&d.a.k.u||"number"===typeof d)if(db||(db=(new M).c()),(d|0)===d&&1/d!==1/-0)c=d|0;else if(ra(d)){c=d;var d=(null===c?x().r:c).f,e=(new J).t(d),f=null===c?x().r:c;e.f===f.f&&e.h===f.h?c=d:(c=null===c?x().r:c,c=c.f^c.h)}else if("number"===typeof d)if(c=d,e=2147483647<+c?
2147483647:-2147483648>+c?-2147483648:+c|0,d=+c,e===d)c=e;else{var e=rb(x(),+c),f=e.f,m=e.h;c=(0>m?-(4294967296*+((0!==f?~m:-m|0)>>>0)+ +((-f|0)>>>0)):4294967296*m+ +(f>>>0))===d?e.f^e.h:xa(ya(),+c)}else c=ta(d);else c=ta(d);d=void 0;c=l(-862048943,c);c=c<<15|c>>>-15|0;c=l(461845907,c);b=d=b^c;d=b<<13|b>>>-13|0;b=-430675100+l(5,d)|0;a=1+a|0}a=b^1;a=l(-2048144789,a^(a>>>16|0));a^=a>>>13|0;a=l(-1028477387,a);a^=a>>>16|0;return a};
U.prototype.a=w({T:0},"scala.scalajs.js.JavaScriptException",{T:1,aa:1,$:1,R:1,b:1,p:1,$a:1,Ya:1,S:1});
}).call(this);
//# sourceMappingURL=background-opt.js.map
